// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5bkoSljZ9tap-LEqk4scO5YpbPC7Cuk',
    appId: '1:772274092976:web:e3ecf52bdaf7e20ce53475',
    messagingSenderId: '772274092976',
    projectId: 'health-30666',
    authDomain: 'health-30666.firebaseapp.com',
    storageBucket: 'health-30666.appspot.com',
    measurementId: 'G-03R7QQ0QH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xPJSGvn5grMdnidoTdy0iumZhnp_oBo',
    appId: '1:772274092976:android:17de4c984372a8d3e53475',
    messagingSenderId: '772274092976',
    projectId: 'health-30666',
    storageBucket: 'health-30666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo7EkrGvyW43DRQk-5gna_kfDCT6svdnQ',
    appId: '1:772274092976:ios:4a3c66bb617c117ce53475',
    messagingSenderId: '772274092976',
    projectId: 'health-30666',
    storageBucket: 'health-30666.appspot.com',
    iosBundleId: 'com.example.medicalCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo7EkrGvyW43DRQk-5gna_kfDCT6svdnQ',
    appId: '1:772274092976:ios:a118750204254e61e53475',
    messagingSenderId: '772274092976',
    projectId: 'health-30666',
    storageBucket: 'health-30666.appspot.com',
    iosBundleId: 'com.example.medicalCareApp.RunnerTests',
  );
}
